// Question banks for Psych! clone.
// Each entry: { prompt, answer }  — players write bluffs, then guess the real `answer`.
const DECKS = {
  adults: {
    name: "Adults",
    emoji: "🍸",
    blurb: "Cheeky fill-in-the-blanks. 18+ humour.",
    questions: [
      { prompt: "In a survey, adults said the #1 thing they secretly do when home alone is ______.", answer: "Talk to their pets in a baby voice" },
      { prompt: "The most common lie people tell on a first date is ______.", answer: "\"I don't usually do this\"" },
      { prompt: "A study found the average person spends 3 whole days of their life ______.", answer: "Looking for the TV remote" },
      { prompt: "The weirdest thing confiscated by airport security last year was a ______.", answer: "Jar of live snails" },
      { prompt: "The most-Googled relationship question at 2am is \"How do I ______?\"", answer: "Tell if my partner is faking sleep" },
      { prompt: "Bartenders say the drink you order secretly reveals that you are ______.", answer: "About to text your ex" },
      { prompt: "The most common excuse used to leave a bad party is ______.", answer: "\"I have to feed my sourdough starter\"" },
      { prompt: "Roommates argue most often about ______.", answer: "Whose turn it is to buy toilet paper" },
      { prompt: "The number one item people forget to pack for a holiday is ______.", answer: "A phone charger" },
      { prompt: "According to hotel staff, the strangest thing guests request is ______.", answer: "A pillow menu with 12 options" },
      { prompt: "The most-returned gift after Valentine's Day is ______.", answer: "A pair of matching pyjamas" },
      { prompt: "People confess their biggest kitchen fear is ______.", answer: "Deep frying anything" },
    ],
  },
  proverbs: {
    name: "Proverbs",
    emoji: "📜",
    blurb: "Finish the classic saying — for real this time.",
    questions: [
      { prompt: "A bird in the hand is worth ______.", answer: "Two in the bush" },
      { prompt: "The early bird catches ______.", answer: "The worm" },
      { prompt: "Don't count your chickens ______.", answer: "Before they hatch" },
      { prompt: "When in Rome, ______.", answer: "Do as the Romans do" },
      { prompt: "A rolling stone gathers ______.", answer: "No moss" },
      { prompt: "People who live in glass houses shouldn't ______.", answer: "Throw stones" },
      { prompt: "You can lead a horse to water but ______.", answer: "You can't make it drink" },
      { prompt: "The pen is mightier than ______.", answer: "The sword" },
      { prompt: "Too many cooks ______.", answer: "Spoil the broth" },
      { prompt: "A watched pot ______.", answer: "Never boils" },
      { prompt: "Curiosity killed ______.", answer: "The cat" },
      { prompt: "Every cloud has ______.", answer: "A silver lining" },
    ],
  },
  story: {
    name: "Story",
    emoji: "📰",
    blurb: "Weird-but-true headlines. Guess how it really ended.",
    questions: [
      { prompt: "A town in Norway installed giant mirrors on a mountain so that residents could finally ______.", answer: "See sunlight in winter" },
      { prompt: "A man in the UK legally changed his name to ______.", answer: "Bacon Double Cheeseburger" },
      { prompt: "In Japan there is a museum entirely dedicated to ______.", answer: "Parasites" },
      { prompt: "A woman won a lawsuit against a company because their product ______.", answer: "Was too addictive to stop eating" },
      { prompt: "A small village elected a ______ as its honorary mayor.", answer: "Goat" },
      { prompt: "Scientists discovered that octopuses will sometimes ______ when they get grumpy.", answer: "Punch fish for no reason" },
      { prompt: "An airline once had to delay a flight because a passenger ______.", answer: "Threw coins into the engine for luck" },
      { prompt: "A library in the US charges no late fees but asks you to ______ instead.", answer: "Read to a shelter dog" },
      { prompt: "A hotel in Sweden is rebuilt every winter entirely out of ______.", answer: "Ice and snow" },
      { prompt: "A man survived being lost at sea for weeks by ______.", answer: "Eating raw fish and turtles" },
      { prompt: "A country once ran out of coins, so shops gave change in ______.", answer: "Sweets and chewing gum" },
      { prompt: "A festival in Spain involves thousands of people throwing ______ at each other.", answer: "Tomatoes" },
    ],
  },
  wordgames: {
    name: "Word Games",
    emoji: "🔤",
    blurb: "Obscure real words. Bluff a definition, spot the truth.",
    questions: [
      { prompt: "Define the real word: \"Petrichor\"", answer: "The pleasant smell of rain on dry earth" },
      { prompt: "Define the real word: \"Gubbins\"", answer: "Miscellaneous bits and bobs" },
      { prompt: "Define the real word: \"Collywobbles\"", answer: "A nervous stomach ache" },
      { prompt: "Define the real word: \"Snollygoster\"", answer: "A shrewd, unprincipled person" },
      { prompt: "Define the real word: \"Widdershins\"", answer: "Moving in an anticlockwise direction" },
      { prompt: "Define the real word: \"Brontide\"", answer: "The low rumble of distant thunder" },
      { prompt: "Define the real word: \"Mumpsimus\"", answer: "Someone who clings to a mistaken belief" },
      { prompt: "Define the real word: \"Nudiustertian\"", answer: "Relating to the day before yesterday" },
      { prompt: "Define the real word: \"Pandiculation\"", answer: "The act of stretching and yawning" },
      { prompt: "Define the real word: \"Ultracrepidarian\"", answer: "One who gives opinions beyond their knowledge" },
      { prompt: "Define the real word: \"Cwtch\"", answer: "A cosy Welsh cuddle" },
      { prompt: "Define the real word: \"Zenzizenzizenzic\"", answer: "A number raised to the eighth power" },
    ],
  },
};
