// Question banks for Psych! clone.
// Each entry: { prompt, answer }  — players write bluffs, then guess the real `answer`.
const DECKS = {
  adults: {
    name: "Adults",
    emoji: "🍸",
    blurb: "Cheeky fill-in-the-blanks. 18+ humour.",
    questions: [
      { prompt: "In a survey, adults said the #1 thing they secretly do when home alone is ______.", answer: "Talk to their pets in a baby voice" },
      { prompt: "The most common lie people tell on a first date is ______.", answer: "\"I don't usually do this\"" },
      { prompt: "A study found the average person spends 3 whole days of their life ______.", answer: "Looking for the TV remote" },
      { prompt: "The weirdest thing confiscated by airport security last year was a ______.", answer: "Jar of live snails" },
      { prompt: "The most-Googled relationship question at 2am is \"How do I ______?\"", answer: "Tell if my partner is faking sleep" },
      { prompt: "Bartenders say the drink you order secretly reveals that you are ______.", answer: "About to text your ex" },
      { prompt: "The most common excuse used to leave a bad party is ______.", answer: "\"I have to feed my sourdough starter\"" },
      { prompt: "Roommates argue most often about ______.", answer: "Whose turn it is to buy toilet paper" },
      { prompt: "The number one item people forget to pack for a holiday is ______.", answer: "A phone charger" },
      { prompt: "According to hotel staff, the strangest thing guests request is ______.", answer: "A pillow menu with 12 options" },
      { prompt: "The most-returned gift after Valentine's Day is ______.", answer: "A pair of matching pyjamas" },
      { prompt: "People confess their biggest kitchen fear is ______.", answer: "Deep frying anything" },
      { prompt: "In a survey, adults said the #1 thing they secretly do when home alone is ______.", answer: "Talk to their pets in a baby voice" },
      { prompt: "The most common lie people tell on a first date is ______.", answer: "\"I don't usually do this\"" },
      { prompt: "The weirdest thing someone has accidentally taken to work is ______.", answer: "Their TV remote" },
      { prompt: "The most embarrassing thing to say during a video call is ______.", answer: "\"I thought you were on mute.\"" },
      { prompt: "The #1 thing people pretend to understand is ______.", answer: "Taxes" },
      { prompt: "The most common excuse for being late is ______.", answer: "Traffic" },
      { prompt: "The worst thing to hear from your doctor is ______.", answer: "\"That's... interesting.\"" },
      { prompt: "A terrible name for a dating app would be ______.", answer: "Last Resort" },
      { prompt: "The first thing people check after dropping their phone is ______.", answer: "The screen" },
      { prompt: "The most awkward thing to forget someone's name during is ______.", answer: "Introducing them" },

      { prompt: "The biggest reason people snoop through someone else's phone is ______.", answer: "Curiosity" },
      { prompt: "The most suspicious thing to hear at 3 AM is ______.", answer: "Someone vacuuming" },
      { prompt: "The strangest thing people collect is ______.", answer: "Hotel shampoo bottles" },
      { prompt: "The #1 thing people regret buying online is ______.", answer: "Clothes that looked better in the pictures" },
      { prompt: "The weirdest thing someone has Googled at 2 AM is ______.", answer: "Can fish get thirsty?" },
      { prompt: "The first thing people do after getting paid is ______.", answer: "Check their bank balance" },
      { prompt: "The worst thing to accidentally text your boss is ______.", answer: "A meme making fun of work" },
      { prompt: "The most common reason people fake being busy is ______.", answer: "To avoid talking to someone" },
      { prompt: "A terrible slogan for a gym would be ______.", answer: "\"Maybe Tomorrow\"" },
      { prompt: "The most awkward place to run into your ex is ______.", answer: "A first date" },

      { prompt: "The weirdest thing people name their Wi-Fi is ______.", answer: "FBI Surveillance Van" },
      { prompt: "The biggest sign someone is bluffing is ______.", answer: "They won't stop talking" },
      { prompt: "The worst thing to hear on an airplane is ______.", answer: "\"Oops.\"" },
      { prompt: "A terrible name for a restaurant would be ______.", answer: "Yesterday's Leftovers" },
      { prompt: "The first thing people notice about a hotel room is ______.", answer: "The bed" },
      { prompt: "The weirdest thing someone has found in their pocket is ______.", answer: "An old french fry" },
      { prompt: "The biggest waste of money people still buy is ______.", answer: "Lottery tickets" },
      { prompt: "The most common thing people forget before leaving home is ______.", answer: "Their keys" },
      { prompt: "The worst thing to hear your GPS say is ______.", answer: "\"Good luck.\"" },
      { prompt: "The first thing people secretly judge at someone's house is ______.", answer: "How clean it is" },

      { prompt: "The most ridiculous thing people argue about online is ______.", answer: "Pineapple on pizza" },
      { prompt: "The #1 thing people pretend to enjoy is ______.", answer: "Networking events" },
      { prompt: "The weirdest thing someone has ever won is ______.", answer: "A lifetime supply of pickles" },
      { prompt: "The first thing people do when they get a haircut is ______.", answer: "Take a selfie" },
      { prompt: "The most awkward thing to accidentally like on social media is ______.", answer: "A post from five years ago" },
      { prompt: "The worst thing to realize halfway through a meeting is ______.", answer: "You're in the wrong meeting" },
      { prompt: "The strangest thing someone has kept for sentimental reasons is ______.", answer: "An old movie ticket" },
      { prompt: "The most common reason people cancel plans is ______.", answer: "They're too tired" },
      { prompt: "The biggest sign someone is lying is ______.", answer: "Avoiding eye contact" },
      { prompt: "The first thing people buy after moving into a new house is ______.", answer: "A shower curtain" },

      { prompt: "The most embarrassing thing to spill on yourself is ______.", answer: "Coffee" },
      { prompt: "The weirdest thing to hear your neighbor doing is ______.", answer: "Practicing opera" },
      { prompt: "The worst thing to forget before a vacation is ______.", answer: "Your passport" },
      { prompt: "The most common thing people lose in their own house is ______.", answer: "The TV remote" },
      { prompt: "The biggest reason people stay awake too late is ______.", answer: "Scrolling on their phone" },
      { prompt: "The weirdest place someone has fallen asleep is ______.", answer: "During a haircut" },
      { prompt: "The most awkward thing to say to a police officer is ______.", answer: "\"Am I in trouble?\"" },
      { prompt: "The first thing people look for in a hotel breakfast is ______.", answer: "Coffee" },
      { prompt: "The funniest excuse for missing work is ______.", answer: "My alarm clock resigned" },
      { prompt: "The #1 thing people wish they could delete from the internet is ______.", answer: "Old social media posts" },



      { prompt: "The biggest red flag on a dating profile is ______.", answer: "No bio at all" },
      { prompt: "The first thing people secretly judge on a first date is ______.", answer: "How they treat the waiter" },
      { prompt: "The most common reason someone gets ghosted is ______.", answer: "They came on too strong" },
      { prompt: "The worst text to accidentally send to your family is ______.", answer: "A message meant for your date" },
      { prompt: "The most embarrassing thing to yell during karaoke is ______.", answer: "The wrong lyrics" },
      { prompt: "The biggest reason friends unfollow each other is ______.", answer: "Too many selfies" },
      { prompt: "The most awkward excuse to leave a bad date is ______.", answer: "\"My friend needs me.\"" },
      { prompt: "The first thing people buy after a breakup is ______.", answer: "Ice cream" },
      { prompt: "The biggest lie people tell after drinking is ______.", answer: "\"I'm totally fine.\"" },
      { prompt: "The worst thing to wake up next to after a party is ______.", answer: "Someone else's phone" },

      { prompt: "The first thing people blame after making a bad decision is ______.", answer: "Alcohol" },
      { prompt: "The weirdest thing someone has confessed after midnight is ______.", answer: "Their childhood crush" },
      { prompt: "The fastest way to ruin a group vacation is ______.", answer: "Arguing about money" },
      { prompt: "The most common thing people steal from hotels is ______.", answer: "Tiny shampoo bottles" },
      { prompt: "The worst roommate habit is ______.", answer: "Never washing dishes" },
      { prompt: "The most suspicious thing to hear through an apartment wall is ______.", answer: "Furniture moving at 2 AM" },
      { prompt: "The biggest reason people delete their dating apps is ______.", answer: "Dating burnout" },
      { prompt: "The funniest thing to accidentally say during a job interview is ______.", answer: "\"I hate mornings.\"" },
      { prompt: "The biggest mistake people make after one too many drinks is ______.", answer: "Texting their ex" },
      { prompt: "The most awkward thing to find in someone else's bathroom is ______.", answer: "A giant mirror with perfect lighting" },

      { prompt: "The first thing people check after a night out is ______.", answer: "Their bank account" },
      { prompt: "The worst thing to realize after sending a risky text is ______.", answer: "It went to the wrong person" },
      { prompt: "The biggest dating deal-breaker is ______.", answer: "Being rude" },
      { prompt: "The weirdest excuse for canceling plans is ______.", answer: "\"My plants need me.\"" },
      { prompt: "The most awkward place to bump into your boss is ______.", answer: "A nightclub" },
      { prompt: "The first thing people hide before guests arrive is ______.", answer: "Laundry" },
      { prompt: "The biggest reason people pretend not to see someone is ______.", answer: "They don't want to talk" },
      { prompt: "The worst thing to accidentally like on Instagram is ______.", answer: "An eight-year-old photo" },
      { prompt: "The most embarrassing thing to forget after staying overnight is ______.", answer: "Your toothbrush" },
      { prompt: "The biggest reason people fake laughing is ______.", answer: "To avoid awkward silence" },

      { prompt: "The first thing people complain about after turning 30 is ______.", answer: "Back pain" },
      { prompt: "The funniest thing someone has blamed on autocorrect is ______.", answer: "A breakup text" },
      { prompt: "The biggest sign someone is flirting is ______.", answer: "Finding excuses to keep talking" },
      { prompt: "The worst thing to spill at a party is ______.", answer: "Red wine" },
      { prompt: "The most common reason people leave a party early is ______.", answer: "They're exhausted" },
      { prompt: "The biggest lie people tell themselves before shopping is ______.", answer: "\"I'm just browsing.\"" },
      { prompt: "The weirdest thing someone has kept from an ex is ______.", answer: "A hoodie" },
      { prompt: "The first thing people regret after online shopping is ______.", answer: "Checking their bank balance" },
      { prompt: "The most awkward thing to overhear on public transport is ______.", answer: "A breakup call" },
      { prompt: "The biggest mistake someone can make on vacation is ______.", answer: "Forgetting their passport" },

      { prompt: "The most embarrassing notification to appear on a shared screen is ______.", answer: "A dating app alert" },
      { prompt: "The worst thing to say after meeting your partner's parents is ______.", answer: "\"So... what's for dinner?\"" },
      { prompt: "The biggest sign someone peaked in college is ______.", answer: "They still wear their college hoodie every day" },
      { prompt: "The funniest thing people suddenly become experts in after two drinks is ______.", answer: "Politics" },
      { prompt: "The first thing people stalk after meeting someone new is ______.", answer: "Their Instagram" },
      { prompt: "The weirdest thing to receive anonymously is ______.", answer: "A potato in the mail" },
      { prompt: "The most common thing people exaggerate about is ______.", answer: "How busy they are" },
      { prompt: "The worst thing to accidentally leave at someone's house is ______.", answer: "Your wallet" },
      { prompt: "The biggest reason people stay in bad relationships is ______.", answer: "Comfort" },
      { prompt: "The most awkward thing to hear someone say in their sleep is ______.", answer: "Someone else's name" },


      { prompt: "The biggest mistake people make after getting a little too confident is ______.", answer: "Texting their crush" },
      { prompt: "The weirdest thing someone has accidentally left in an Uber is ______.", answer: "A wig" },
      { prompt: "The first thing people secretly do after getting home from work is ______.", answer: "Take off their pants" },
      { prompt: "The worst thing to hear after saying 'I love you' is ______.", answer: "\"Thank you.\"" },
      { prompt: "The most awkward way to discover you were blocked is ______.", answer: "Looking up their profile" },
      { prompt: "The biggest reason people fake being sick is ______.", answer: "To avoid work" },
      { prompt: "The weirdest thing someone has ordered after midnight is ______.", answer: "Twenty chicken nuggets and one salad" },
      { prompt: "The first thing people delete before handing over their phone is ______.", answer: "Their search history" },
      { prompt: "The most embarrassing thing to accidentally say during a toast is ______.", answer: "The wrong person's name" },
      { prompt: "The biggest reason people stop going to the gym is ______.", answer: "Laziness" },

      { prompt: "The worst thing to receive at 2 AM is ______.", answer: "\"We need to talk.\"" },
      { prompt: "The funniest thing to overhear in a public restroom is ______.", answer: "Someone practicing a speech" },
      { prompt: "The biggest sign someone is lying about their age is ______.", answer: "Doing the math too slowly" },
      { prompt: "The first thing people notice when they walk into a messy apartment is ______.", answer: "The smell" },
      { prompt: "The weirdest thing people have admitted during a drinking game is ______.", answer: "Their celebrity crush" },
      { prompt: "The worst excuse for forgetting an anniversary is ______.", answer: "\"I thought it was next week.\"" },
      { prompt: "The biggest reason people don't answer phone calls anymore is ______.", answer: "They hate talking on the phone" },
      { prompt: "The most embarrassing thing to accidentally post online is ______.", answer: "A screenshot meant for a friend" },
      { prompt: "The first thing people secretly compare on a date is ______.", answer: "Height" },
      { prompt: "The biggest red flag in a group chat is ______.", answer: "\"Can we all talk?\"" },

      { prompt: "The weirdest thing someone has kept in their fridge is ______.", answer: "Expired ketchup packets" },
      { prompt: "The first thing people blame after a bad haircut is ______.", answer: "The barber" },
      { prompt: "The worst thing to hear while meeting your partner's friends is ______.", answer: "\"We've heard a lot about you.\"" },
      { prompt: "The biggest reason someone lies about their salary is ______.", answer: "To impress people" },
      { prompt: "The funniest thing someone has done to avoid paying the bill is ______.", answer: "Pretended to get a phone call" },
      { prompt: "The first thing people notice about a bad Tinder profile is ______.", answer: "Blurry photos" },
      { prompt: "The most awkward thing to accidentally call your teacher is ______.", answer: "Mom" },
      { prompt: "The weirdest thing someone has hidden under their bed is ______.", answer: "Holiday gifts" },
      { prompt: "The biggest reason people return from vacation more tired is ______.", answer: "Trying to do too much" },
      { prompt: "The worst thing to accidentally leave open on your laptop is ______.", answer: "A dating website" },

      { prompt: "The first thing people secretly do before guests arrive is ______.", answer: "Hide the clutter" },
      { prompt: "The biggest lie people tell after shopping is ______.", answer: "\"It was on sale.\"" },
      { prompt: "The funniest thing to hear at a wedding is ______.", answer: "\"Does anyone object?\"" },
      { prompt: "The weirdest thing someone has forgotten in a hotel room is ______.", answer: "Their shoes" },
      { prompt: "The first thing people check after a bad first date is ______.", answer: "Whether they got unmatched" },
      { prompt: "The biggest mistake people make after getting promoted is ______.", answer: "Acting like the boss" },
      { prompt: "The worst thing to hear from your roommate is ______.", answer: "\"Can we talk about rent?\"" },
      { prompt: "The funniest thing people suddenly become after watching one documentary is ______.", answer: "An expert" },
      { prompt: "The biggest reason someone pretends not to recognize you is ______.", answer: "They forgot your name" },
      { prompt: "The weirdest thing someone has used as a bookmark is ______.", answer: "A slice of cheese" },

      { prompt: "The first thing people secretly judge at a party is ______.", answer: "The snacks" },
      { prompt: "The biggest mistake someone can make on a first vacation together is ______.", answer: "Overplanning everything" },
      { prompt: "The worst thing to accidentally send to the family group chat is ______.", answer: "A meme meant for friends" },
      { prompt: "The funniest thing people claim they can cook is ______.", answer: "Restaurant-quality steak" },
      { prompt: "The first thing people regret after a night out is ______.", answer: "Checking their bank statement" },
      { prompt: "The biggest reason someone leaves a group chat is ______.", answer: "Too many notifications" },
      { prompt: "The weirdest thing someone has found in a rental apartment is ______.", answer: "A fake mustache collection" },
      { prompt: "The worst thing to hear before opening your credit card bill is ______.", answer: "\"Remember last weekend?\"" },
      { prompt: "The first thing people secretly hope for at a party is ______.", answer: "Free food" },
      { prompt: "The biggest sign someone has had one drink too many is ______.", answer: "They become everyone's best friend" },



      { prompt: "The first thing people secretly do after matching on a dating app is ______.", answer: "Stalk their Instagram" },
      { prompt: "The biggest reason someone gets left on 'Read' is ______.", answer: "They sent a boring message" },
      { prompt: "The most awkward thing to accidentally call your partner is ______.", answer: "Your ex's name" },
      { prompt: "The biggest lie people tell before going out is ______.", answer: "\"I'll only have one drink.\"" },
      { prompt: "The weirdest thing someone has done to impress a crush is ______.", answer: "Pretended to like hiking" },
      { prompt: "The first thing people secretly judge at a house party is ______.", answer: "The alcohol selection" },
      { prompt: "The worst thing to hear after a one-night party is ______.", answer: "\"We should split the cleaning.\"" },
      { prompt: "The biggest relationship argument starts because of ______.", answer: "Dirty dishes" },
      { prompt: "The funniest thing to accidentally say to your boss after drinking is ______.", answer: "\"You're actually pretty cool.\"" },
      { prompt: "The biggest mistake people make after midnight is ______.", answer: "Texting their ex" },

      { prompt: "The weirdest thing someone has blamed on being drunk is ______.", answer: "Buying a pet" },
      { prompt: "The first thing people hide before their parents visit is ______.", answer: "Empty bottles" },
      { prompt: "The biggest red flag when meeting someone's friends is ______.", answer: "Nobody seems to like them" },
      { prompt: "The most embarrassing thing to wake up remembering is ______.", answer: "A drunk speech" },
      { prompt: "The worst thing to find in your Uber history is ______.", answer: "A trip you don't remember" },
      { prompt: "The biggest sign someone is flirting is ______.", answer: "Laughing at every joke" },
      { prompt: "The funniest excuse for walking away from an awkward conversation is ______.", answer: "\"I think my Uber is here.\"" },
      { prompt: "The first thing people secretly Google after a bad date is ______.", answer: "Dating advice" },
      { prompt: "The weirdest compliment someone could receive at a bar is ______.", answer: "\"You look trustworthy.\"" },
      { prompt: "The biggest reason people suddenly become 'busy' is ______.", answer: "Someone they don't like showed up" },

      { prompt: "The worst thing to hear after introducing your partner is ______.", answer: "\"You can do better.\"" },
      { prompt: "The biggest mistake someone makes at karaoke is ______.", answer: "Choosing Bohemian Rhapsody" },
      { prompt: "The funniest thing someone has cried about after drinking is ______.", answer: "A dog video" },
      { prompt: "The first thing people secretly compare with friends is ______.", answer: "Salary" },
      { prompt: "The biggest reason someone gets kicked out of a group chat is ______.", answer: "Too much drama" },
      { prompt: "The weirdest thing to find in a shared apartment fridge is ______.", answer: "Someone else's birthday cake" },
      { prompt: "The worst thing to receive while on vacation is ______.", answer: "A work email" },
      { prompt: "The biggest dating profile turn-off is ______.", answer: "Only group photos" },
      { prompt: "The funniest thing to accidentally say during a wedding speech is ______.", answer: "Mention the ex" },
      { prompt: "The first thing people secretly judge after visiting a friend's bathroom is ______.", answer: "The towels" },

      { prompt: "The biggest reason people pretend not to recognize someone is ______.", answer: "They owe them money" },
      { prompt: "The weirdest thing someone has packed for vacation is ______.", answer: "An air fryer" },
      { prompt: "The first thing people do after deleting a dating app is ______.", answer: "Reinstall it a week later" },
      { prompt: "The biggest mistake someone can make during a family dinner is ______.", answer: "Bringing up politics" },
      { prompt: "The funniest thing someone has accidentally worn inside out all day is ______.", answer: "Their shirt" },
      { prompt: "The biggest sign someone is trying too hard to look cool is ______.", answer: "Using too much slang" },
      { prompt: "The weirdest thing people suddenly become experts in after two drinks is ______.", answer: "Relationships" },
      { prompt: "The worst thing to hear while checking your bank account is ______.", answer: "\"Payment declined.\"" },
      { prompt: "The first thing people secretly check before posting a selfie is ______.", answer: "How many likes their last post got" },
      { prompt: "The biggest reason people fake confidence is ______.", answer: "They're nervous" },

      { prompt: "The funniest thing to accidentally reveal during 'Never Have I Ever' is ______.", answer: "An old crush" },
      { prompt: "The biggest mistake people make after moving in together is ______.", answer: "Not discussing chores" },
      { prompt: "The weirdest thing someone has found after cleaning their room is ______.", answer: "Money in an old jacket" },
      { prompt: "The first thing people secretly hope for at an office party is ______.", answer: "Free drinks" },
      { prompt: "The worst thing to hear after saying 'Trust me' is ______.", answer: "\"Absolutely not.\"" },
      { prompt: "The biggest reason people cancel a second date is ______.", answer: "No chemistry" },
      { prompt: "The funniest thing someone has blamed on Mercury retrograde is ______.", answer: "Getting dumped" },
      { prompt: "The first thing people secretly judge at brunch is ______.", answer: "Who orders the most expensive meal" },
      { prompt: "The biggest reason adults miss being kids is ______.", answer: "No bills" },
      { prompt: "The one thing almost everyone has done but would never admit publicly is ______.", answer: "Pretended to know what was going on" }


    ],

  },


  proverbs: {
    name: "Proverbs",
    emoji: "📜",
    blurb: "Finish the classic saying — for real this time.",
    questions: [
      { prompt: "A bird in the hand is worth ______.", answer: "Two in the bush" },
      { prompt: "The early bird catches ______.", answer: "The worm" },
      { prompt: "Don't count your chickens ______.", answer: "Before they hatch" },
      { prompt: "When in Rome, ______.", answer: "Do as the Romans do" },
      { prompt: "A rolling stone gathers ______.", answer: "No moss" },
      { prompt: "People who live in glass houses shouldn't ______.", answer: "Throw stones" },
      { prompt: "You can lead a horse to water but ______.", answer: "You can't make it drink" },
      { prompt: "The pen is mightier than ______.", answer: "The sword" },
      { prompt: "Too many cooks ______.", answer: "Spoil the broth" },
      { prompt: "A watched pot ______.", answer: "Never boils" },
      { prompt: "Curiosity killed ______.", answer: "The cat" },
      { prompt: "Every cloud has ______.", answer: "A silver lining" },
      { prompt: "A chain is only as strong as its ______.", answer: "Weakest link" },
      { prompt: "A fool and his money are soon ______.", answer: "Parted" },
      { prompt: "A house divided against itself cannot ______.", answer: "Stand" },
      { prompt: "A jack of all trades is master of ______.", answer: "None" },
      { prompt: "A leopard cannot change its ______.", answer: "Spots" },
      { prompt: "A miss is as good as a ______.", answer: "Mile" },
      { prompt: "A rising tide lifts all ______.", answer: "Boats" },
      { prompt: "A rolling stone gathers no ______.", answer: "Moss" },
      { prompt: "A stitch in time saves ______.", answer: "Nine" },
      { prompt: "A watched pot never ______.", answer: "Boils" },

      { prompt: "Actions speak louder than ______.", answer: "Words" },
      { prompt: "All good things must come to an ______.", answer: "End" },
      { prompt: "All that glitters is not ______.", answer: "Gold" },
      { prompt: "An apple a day keeps the ______ away.", answer: "Doctor" },
      { prompt: "An ounce of prevention is worth a pound of ______.", answer: "Cure" },
      { prompt: "As you sow, so shall you ______.", answer: "Reap" },
      { prompt: "Barking dogs seldom ______.", answer: "Bite" },
      { prompt: "Beauty is in the eye of the ______.", answer: "Beholder" },
      { prompt: "Better late than ______.", answer: "Never" },
      { prompt: "Better safe than ______.", answer: "Sorry" },

      { prompt: "Blood is thicker than ______.", answer: "Water" },
      { prompt: "Curiosity killed the ______.", answer: "Cat" },
      { prompt: "Don't bite the hand that ______ you.", answer: "Feeds" },
      { prompt: "Don't count your chickens before they ______.", answer: "Hatch" },
      { prompt: "Don't judge a book by its ______.", answer: "Cover" },
      { prompt: "Don't put all your eggs in one ______.", answer: "Basket" },
      { prompt: "Every cloud has a silver ______.", answer: "Lining" },
      { prompt: "Every dog has its ______.", answer: "Day" },
      { prompt: "Fortune favors the ______.", answer: "Bold" },
      { prompt: "Good things come to those who ______.", answer: "Wait" },

      { prompt: "Honesty is the best ______.", answer: "Policy" },
      { prompt: "If it ain't broke, don't ______ it.", answer: "Fix" },
      { prompt: "If the shoe fits, ______ it.", answer: "Wear" },
      { prompt: "Ignorance is ______.", answer: "Bliss" },
      { prompt: "Keep your friends close and your enemies ______.", answer: "Closer" },
      { prompt: "Kill two birds with one ______.", answer: "Stone" },
      { prompt: "Look before you ______.", answer: "Leap" },
      { prompt: "Misery loves ______.", answer: "Company" },
      { prompt: "Necessity is the mother of ______.", answer: "Invention" },
      { prompt: "No news is good ______.", answer: "News" },

      { prompt: "No pain, no ______.", answer: "Gain" },
      { prompt: "Once bitten, twice ______.", answer: "Shy" },
      { prompt: "Out of sight, out of ______.", answer: "Mind" },
      { prompt: "Practice makes ______.", answer: "Perfect" },
      { prompt: "Rome wasn't built in a ______.", answer: "Day" },
      { prompt: "The grass is always greener on the other side of the ______.", answer: "Fence" },
      { prompt: "The pen is mightier than the ______.", answer: "Sword" },
      { prompt: "There is no smoke without ______.", answer: "Fire" },
      { prompt: "Too many cooks spoil the ______.", answer: "Broth" },
      { prompt: "Where there's a will, there's a ______.", answer: "Way" },
      { prompt: "Absence makes the heart grow ______.", answer: "Fonder" },
      { prompt: "All's fair in love and ______.", answer: "War" },
      { prompt: "All's well that ends ______.", answer: "Well" },
      { prompt: "As busy as a ______.", answer: "Bee" },
      { prompt: "As cool as a ______.", answer: "Cucumber" },
      { prompt: "As the twig is bent, so grows the ______.", answer: "Tree" },
      { prompt: "Beggars can't be ______.", answer: "Choosers" },
      { prompt: "Birds of a feather flock ______.", answer: "Together" },
      { prompt: "Charity begins at ______.", answer: "Home" },
      { prompt: "Cleanliness is next to ______.", answer: "Godliness" },

      { prompt: "Desperate times call for desperate ______.", answer: "Measures" },
      { prompt: "Easy come, easy ______.", answer: "Go" },
      { prompt: "Empty vessels make the most ______.", answer: "Noise" },
      { prompt: "Every rose has its ______.", answer: "Thorn" },
      { prompt: "Experience is the best ______.", answer: "Teacher" },
      { prompt: "Failing to plan is planning to ______.", answer: "Fail" },
      { prompt: "Familiarity breeds ______.", answer: "Contempt" },
      { prompt: "Give credit where credit is ______.", answer: "Due" },
      { prompt: "Great minds think ______.", answer: "Alike" },
      { prompt: "Half a loaf is better than ______.", answer: "None" },

      { prompt: "He who laughs last laughs ______.", answer: "Best" },
      { prompt: "He who lives by the sword shall die by the ______.", answer: "Sword" },
      { prompt: "Hindsight is ______.", answer: "Twenty-twenty" },
      { prompt: "If the mountain won't come to Muhammad, Muhammad must go to the ______.", answer: "Mountain" },
      { prompt: "It's always darkest before the ______.", answer: "Dawn" },
      { prompt: "It's no use crying over spilled ______.", answer: "Milk" },
      { prompt: "Keep your powder ______.", answer: "Dry" },
      { prompt: "Let sleeping dogs ______.", answer: "Lie" },
      { prompt: "Lightning never strikes the same place ______.", answer: "Twice" },
      { prompt: "Little strokes fell great ______.", answer: "Oaks" },

      { prompt: "Make hay while the sun ______.", answer: "Shines" },
      { prompt: "Many hands make light ______.", answer: "Work" },
      { prompt: "Money doesn't grow on ______.", answer: "Trees" },
      { prompt: "Never look a gift horse in the ______.", answer: "Mouth" },
      { prompt: "No man is an ______.", answer: "Island" },
      { prompt: "Nothing ventured, nothing ______.", answer: "Gained" },
      { prompt: "Old habits die ______.", answer: "Hard" },
      { prompt: "One good turn deserves ______.", answer: "Another" },
      { prompt: "Opportunity seldom knocks ______.", answer: "Twice" },
      { prompt: "People who live in glass houses shouldn't throw ______.", answer: "Stones" },

      { prompt: "Possession is nine-tenths of the ______.", answer: "Law" },
      { prompt: "Prevention is better than ______.", answer: "Cure" },
      { prompt: "Still waters run ______.", answer: "Deep" },
      { prompt: "Strike while the iron is ______.", answer: "Hot" },
      { prompt: "The best things in life are ______.", answer: "Free" },
      { prompt: "The bigger they are, the harder they ______.", answer: "Fall" },
      { prompt: "The devil is in the ______.", answer: "Details" },
      { prompt: "The proof of the pudding is in the ______.", answer: "Eating" },
      { prompt: "Time and tide wait for no ______.", answer: "Man" },
      { prompt: "Two heads are better than ______.", answer: "One" },
      { prompt: "A bad workman blames his ______.", answer: "Tools" },
      { prompt: "A bird in the hand is worth two in the ______.", answer: "Bush" },
      { prompt: "A burnt child dreads the ______.", answer: "Fire" },
      { prompt: "A drowning man will clutch at ______.", answer: "Straws" },
      { prompt: "A friend in need is a friend ______.", answer: "Indeed" },
      { prompt: "A good beginning makes a good ______.", answer: "Ending" },
      { prompt: "A little learning is a dangerous ______.", answer: "Thing" },
      { prompt: "A penny saved is a penny ______.", answer: "Earned" },
      { prompt: "A picture is worth a thousand ______.", answer: "Words" },
      { prompt: "A smooth sea never made a skilled ______.", answer: "Sailor" },

      { prompt: "A soft answer turns away ______.", answer: "Wrath" },
      { prompt: "A trouble shared is a trouble ______.", answer: "Halved" },
      { prompt: "Adversity makes strange ______.", answer: "Bedfellows" },
      { prompt: "All roads lead to ______.", answer: "Rome" },
      { prompt: "All's well that ends ______.", answer: "Well" },
      { prompt: "An idle mind is the devil's ______.", answer: "Workshop" },
      { prompt: "Any port in a ______.", answer: "Storm" },
      { prompt: "April showers bring May ______.", answer: "Flowers" },
      { prompt: "Ask no questions and hear no ______.", answer: "Lies" },
      { prompt: "Attack is the best form of ______.", answer: "Defense" },

      { prompt: "Bad news travels ______.", answer: "Fast" },
      { prompt: "Behind every great man is a great ______.", answer: "Woman" },
      { prompt: "Better the devil you know than the devil you ______.", answer: "Don't" },
      { prompt: "Brevity is the soul of ______.", answer: "Wit" },
      { prompt: "Cross that bridge when you come to ______.", answer: "It" },
      { prompt: "Cut your coat according to your ______.", answer: "Cloth" },
      { prompt: "Dead men tell no ______.", answer: "Tales" },
      { prompt: "Don't cast pearls before ______.", answer: "Swine" },
      { prompt: "Don't change horses in mid-______.", answer: "Stream" },
      { prompt: "Don't cross the bridge until you come to ______.", answer: "It" },

      { prompt: "Don't make a mountain out of a ______.", answer: "Molehill" },
      { prompt: "Every man has his ______.", answer: "Price" },
      { prompt: "Every man is the architect of his own ______.", answer: "Fortune" },
      { prompt: "First come, first ______.", answer: "Served" },
      { prompt: "Forewarned is ______.", answer: "Forearmed" },
      { prompt: "Give a man enough rope and he will hang ______.", answer: "Himself" },
      { prompt: "Good fences make good ______.", answer: "Neighbors" },
      { prompt: "He who hesitates is ______.", answer: "Lost" },
      { prompt: "If wishes were horses, beggars would ______.", answer: "Ride" },
      { prompt: "In for a penny, in for a ______.", answer: "Pound" },

      { prompt: "It never rains but it ______.", answer: "Pours" },
      { prompt: "It's an ill wind that blows nobody ______.", answer: "Good" },
      { prompt: "Justice delayed is justice ______.", answer: "Denied" },
      { prompt: "Knowledge is ______.", answer: "Power" },
      { prompt: "Least said, soonest ______.", answer: "Mended" },
      { prompt: "Let bygones be ______.", answer: "Bygones" },
      { prompt: "Life begins at ______.", answer: "Forty" },
      { prompt: "Like father, like ______.", answer: "Son" },
      { prompt: "Live and let ______.", answer: "Live" },
      { prompt: "Love is ______.", answer: "Blind" },
      { prompt: "A hungry belly has no ______.", answer: "Ears" },
      { prompt: "A nod is as good as a wink to a ______.", answer: "Blind horse" },
      { prompt: "A fox should not be on the jury at a ______.", answer: "Goose's trial" },
      { prompt: "A shut mouth catches no ______.", answer: "Flies" },
      { prompt: "A silent dog is the first to ______.", answer: "Bite" },
      { prompt: "An empty sack cannot stand ______.", answer: "Upright" },
      { prompt: "Better an egg today than a ______ tomorrow.", answer: "Hen" },
      { prompt: "Better bend than ______.", answer: "Break" },
      { prompt: "Better lose the saddle than the ______.", answer: "Horse" },
      { prompt: "By the street of 'By-and-By,' one arrives at the house of ______.", answer: "Never" },

      { prompt: "Cats hide their ______.", answer: "Claws" },
      { prompt: "Don't burn your house to get rid of a ______.", answer: "Mouse" },
      { prompt: "Don't throw away the old bucket until you know whether the new one ______.", answer: "Holds water" },
      { prompt: "Even a worm will ______.", answer: "Turn" },
      { prompt: "Every ass loves to hear himself ______.", answer: "Bray" },
      { prompt: "Every path has its ______.", answer: "Puddle" },
      { prompt: "Fish begin to stink at the ______.", answer: "Head" },
      { prompt: "Go to bed with dogs and wake up with ______.", answer: "Fleas" },
      { prompt: "Good wine needs no ______.", answer: "Bush" },
      { prompt: "He that cannot dance says the ______ is crooked.", answer: "Floor" },

      { prompt: "He who chases two rabbits catches ______.", answer: "Neither" },
      { prompt: "He who has a why to live can bear almost any ______.", answer: "How" },
      { prompt: "He who sups with the devil should have a long ______.", answer: "Spoon" },
      { prompt: "If you lie down with dogs, you get up with ______.", answer: "Fleas" },
      { prompt: "It is a poor bird that fouls its own ______.", answer: "Nest" },
      { prompt: "Little pitchers have big ______.", answer: "Ears" },
      { prompt: "Never buy a pig in a ______.", answer: "Poke" },
      { prompt: "No bees, no ______.", answer: "Honey" },
      { prompt: "One year's seeding makes seven years' ______.", answer: "Weeding" },
      { prompt: "Only the wearer knows where the shoe ______.", answer: "Pinches" },

      { prompt: "Smooth waters do not make skillful ______.", answer: "Sailors" },
      { prompt: "The apple never falls far from the ______.", answer: "Tree" },
      { prompt: "The bait hides the ______.", answer: "Hook" },
      { prompt: "The cowl does not make the ______.", answer: "Monk" },
      { prompt: "The dog that fetches will also ______.", answer: "Carry" },
      { prompt: "The empty wagon makes the most ______.", answer: "Noise" },
      { prompt: "The higher the monkey climbs, the more he shows his ______.", answer: "Tail" },
      { prompt: "The mills of God grind slowly, but exceedingly ______.", answer: "Fine" },
      { prompt: "The squeaky wheel gets the ______.", answer: "Grease" },
      { prompt: "There are many ways to skin a ______.", answer: "Cat" },

      { prompt: "There is many a slip between the cup and the ______.", answer: "Lip" },
      { prompt: "Those who sleep with dogs rise with ______.", answer: "Fleas" },
      { prompt: "To a man with a hammer, everything looks like a ______.", answer: "Nail" },
      { prompt: "Walls have ______.", answer: "Ears" },
      { prompt: "What cannot be cured must be ______.", answer: "Endured" },
      { prompt: "When elephants fight, it is the grass that ______.", answer: "Suffers" },
      { prompt: "Where there is honey there are ______.", answer: "Flies" },
      { prompt: "You can't make a silk purse out of a sow's ______.", answer: "Ear" },
      { prompt: "You cannot clap with one ______.", answer: "Hand" },
      { prompt: "Zeal without knowledge is a runaway ______.", answer: "Horse" },
    ],
  },



  story: {
    name: "Story",
    emoji: "📰",
    blurb: "Weird-but-true headlines. Guess how it really ended.",
    questions: [
      { prompt: "A town in Norway installed giant mirrors on a mountain so that residents could finally ______.", answer: "See sunlight in winter" },
      { prompt: "A man in the UK legally changed his name to ______.", answer: "Bacon Double Cheeseburger" },
      { prompt: "In Japan there is a museum entirely dedicated to ______.", answer: "Parasites" },
      { prompt: "A woman won a lawsuit against a company because their product ______.", answer: "Was too addictive to stop eating" },
      { prompt: "A small village elected a ______ as its honorary mayor.", answer: "Goat" },
      { prompt: "Scientists discovered that octopuses will sometimes ______ when they get grumpy.", answer: "Punch fish for no reason" },
      { prompt: "An airline once had to delay a flight because a passenger ______.", answer: "Threw coins into the engine for luck" },
      { prompt: "A library in the US charges no late fees but asks you to ______ instead.", answer: "Read to a shelter dog" },
      { prompt: "A hotel in Sweden is rebuilt every winter entirely out of ______.", answer: "Ice and snow" },
      { prompt: "A man survived being lost at sea for weeks by ______.", answer: "Eating raw fish and turtles" },
      { prompt: "A country once ran out of coins, so shops gave change in ______.", answer: "Sweets and chewing gum" },
      { prompt: "A festival in Spain involves thousands of people throwing ______ at each other.", answer: "Tomatoes" },
      { prompt: "A town in Norway installed giant mirrors on a mountain so that residents could finally ______.", answer: "See sunlight in winter" },
      { prompt: "A Japanese train company once apologized because a train departed ______.", answer: "20 seconds early" },
      { prompt: "A Canadian man survived being struck by lightning not once, but ______.", answer: "Seven times" },
      { prompt: "An airport in Alaska employs dogs to keep ______ away from airplanes.", answer: "Birds" },
      { prompt: "A museum once accidentally displayed a pair of glasses because visitors thought it was ______.", answer: "An exhibit" },
      { prompt: "The CIA once spent years trying to train cats to ______.", answer: "Spy on people" },
      { prompt: "A Dutch village painted fake road markings to slow down ______.", answer: "Speeding drivers" },
      { prompt: "A man accidentally bought his own stolen car after recognizing ______.", answer: "The same air freshener and scratches" },
      { prompt: "A Swedish hotel lets guests spend the night inside a giant ______.", answer: "Treehouse" },
      { prompt: "Scientists once taught rats to play ______.", answer: "Hide-and-seek" },

      { prompt: "A family discovered a fortune hidden inside a ______ they bought at a flea market.", answer: "Painting" },
      { prompt: "An Australian police department had to warn people not to drive while ______.", answer: "Balancing coffee on the steering wheel" },
      { prompt: "A zoo had to temporarily close because someone stole ______.", answer: "A parrot that greeted visitors" },
      { prompt: "An Italian village offers money to anyone willing to ______ there.", answer: "Move and live" },
      { prompt: "NASA once lost contact with a spacecraft because someone forgot to ______.", answer: "Convert the measurement units" },
      { prompt: "A man spent years digging a tunnel under his house just to build a ______.", answer: "Secret basement" },
      { prompt: "A city in Germany installed tiny traffic lights just for ______.", answer: "Ducks" },
      { prompt: "An escaped tortoise was finally found after ______.", answer: "Nine months" },
      { prompt: "A woman unknowingly carried a lottery ticket in her purse worth ______.", answer: "Millions of dollars" },
      { prompt: "A restaurant became famous for serving customers entirely in ______.", answer: "Complete darkness" },

      { prompt: "A man survived drifting at sea by eating ______.", answer: "Raw fish" },
      { prompt: "Scientists discovered that octopuses sometimes ______ when bored.", answer: "Throw objects at fish" },
      { prompt: "A town in Spain celebrates a festival where people throw ______ at each other.", answer: "Tomatoes" },
      { prompt: "A school accidentally ordered enough textbooks for the next ______.", answer: "Twenty years" },
      { prompt: "A couple found a hidden room behind their bookshelf containing ______.", answer: "A secret staircase" },
      { prompt: "An Icelandic app helps prevent people from accidentally ______.", answer: "Dating relatives" },
      { prompt: "A man received hundreds of packages after an online shopping error listed his home as ______.", answer: "The return address" },
      { prompt: "A library book was finally returned after being overdue by ______.", answer: "More than 100 years" },
      { prompt: "A dog became mayor of a small American town because ______.", answer: "It won the local election fundraiser" },
      { prompt: "Scientists discovered sharks can recognize ______.", answer: "Human faces" },

      { prompt: "A British man accidentally won a marathon after ______.", answer: "Taking the wrong turn that turned out to be correct" },
      { prompt: "A museum employee accidentally threw away an artwork because it looked like ______.", answer: "Trash" },
      { prompt: "An apartment building installed vending machines that sell ______ instead of snacks.", answer: "Fresh eggs" },
      { prompt: "A city built an underground tunnel just for ______.", answer: "Crabs" },
      { prompt: "A fisherman caught a message in a bottle that had been floating for ______.", answer: "Over 100 years" },
      { prompt: "A bakery became famous after accidentally creating ______.", answer: "A giant cinnamon roll" },
      { prompt: "A bank robber was caught because he stopped to ______.", answer: "Argue about parking" },
      { prompt: "An elephant escaped a circus and wandered into a ______.", answer: "Supermarket parking lot" },
      { prompt: "A university accidentally emailed acceptance letters to ______.", answer: "Thousands of rejected applicants" },
      { prompt: "A mountain climber reached the summit only to discover someone had left ______.", answer: "A couch" },

      { prompt: "A town banned snowball fights because they were legally classified as ______.", answer: "Missiles" },
      { prompt: "A man accidentally proposed using a ring hidden inside ______.", answer: "A milkshake" },
      { prompt: "Scientists found that cows produce more milk when they listen to ______.", answer: "Calming music" },
      { prompt: "A cruise ship turned around because a passenger forgot ______.", answer: "Their passport" },
      { prompt: "A thief returned stolen money with an apology after learning it belonged to ______.", answer: "A charity" },
      { prompt: "An office building installed slides so employees could ______.", answer: "Travel between floors" },
      { prompt: "A museum hired a full-time employee whose only job was to ______.", answer: "Scare away pigeons" },
      { prompt: "A hiker discovered an ancient treasure after tripping over ______.", answer: "A rock" },
      { prompt: "A company accidentally paid an employee 300 times their salary because of ______.", answer: "A typing error" },
      { prompt: "A man found out he'd been declared dead after trying to ______.", answer: "Renew his driver's license" },

      { prompt: "A man in France accidentally discovered a fortune while trying to ______.", answer: "Fix a wall in his house" },
      { prompt: "An airport once delayed flights because a turtle wandered onto the ______.", answer: "Runway" },
      { prompt: "A woman inherited a house only to discover it contained ______.", answer: "A hidden underground bunker" },
      { prompt: "A police department asked people to stop calling 911 because they couldn't ______.", answer: "Remember their Facebook password" },
      { prompt: "A museum displayed a banana taped to a wall that later sold for ______.", answer: "Thousands of dollars" },
      { prompt: "A man accidentally became a local celebrity after appearing in the background of ______.", answer: "Hundreds of tourists' photos" },
      { prompt: "A city had to issue a warning after people kept trying to ______.", answer: "Pet wild bison" },
      { prompt: "Scientists found that pigeons can recognize ______.", answer: "Individual human faces" },
      { prompt: "A man spent years building a castle entirely out of ______.", answer: "Recycled bottles" },
      { prompt: "A zoo had to separate two parrots because they wouldn't stop ______.", answer: "Swearing at visitors" },

      { prompt: "A woman accidentally threw away a hard drive containing ______.", answer: "Millions in cryptocurrency" },
      { prompt: "A bakery sold out after accidentally making bread shaped like ______.", answer: "A dinosaur" },
      { prompt: "A town became famous because its traffic circle looked exactly like ______.", answer: "A giant smiley face" },
      { prompt: "An escaped cow managed to avoid capture for ______.", answer: "Several months" },
      { prompt: "A man found a message in a bottle that had traveled from ______.", answer: "Another continent" },
      { prompt: "A school canceled classes because ______ invaded the building.", answer: "Thousands of bees" },
      { prompt: "A driver got stuck following GPS directions into ______.", answer: "A river" },
      { prompt: "A couple bought a cheap house and later found ______ hidden inside.", answer: "A room full of antiques" },
      { prompt: "Scientists discovered that crows can remember ______.", answer: "People who were mean to them" },
      { prompt: "A small town holds an annual festival celebrating ______.", answer: "A giant potato" },

      { prompt: "A man accidentally boarded the wrong flight and ended up in ______.", answer: "The wrong country" },
      { prompt: "A bank accidentally credited a customer with ______.", answer: "Millions of dollars" },
      { prompt: "A library had to remind visitors not to use ______ as bookmarks.", answer: "Slices of cheese" },
      { prompt: "A tourist was fined after trying to steal ______ from a historic site.", answer: "A brick" },
      { prompt: "An office accidentally ordered ______ instead of printer paper.", answer: "10,000 envelopes" },
      { prompt: "A dog became famous after helping police find ______.", answer: "Missing hikers" },
      { prompt: "A fisherman reeled in a safe containing ______.", answer: "Cash" },
      { prompt: "A town painted blue lines on roads to reduce ______.", answer: "Speeding" },
      { prompt: "An amusement park once shut down because of ______.", answer: "A family of ducks" },
      { prompt: "A man discovered he had been paying someone else's ______ for years.", answer: "Electric bill" },

      { prompt: "Scientists discovered dolphins sometimes give each other ______.", answer: "Names" },
      { prompt: "A grocery store became famous for selling ______ in a vending machine.", answer: "Fresh cake" },
      { prompt: "A city installed tiny bridges specifically for ______.", answer: "Squirrels" },
      { prompt: "A woman won a cooking contest using ______.", answer: "A recipe from the back of a package" },
      { prompt: "A police chase ended when the suspect stopped to ______.", answer: "Buy gas" },
      { prompt: "An employee accidentally sent a company-wide email containing ______.", answer: "A meme" },
      { prompt: "A museum created an exhibit entirely about ______.", answer: "Broken relationships" },
      { prompt: "A farmer discovered a perfectly round ______ growing in his field.", answer: "Square watermelon" },
      { prompt: "A hotel offered guests the chance to sleep inside ______.", answer: "An airplane" },
      { prompt: "A man found out he'd been famous online for years because of ______.", answer: "An old stock photo" },

      { prompt: "A school principal became an internet sensation after ______.", answer: "Dancing with students" },
      { prompt: "A town changed its name for one day to celebrate ______.", answer: "A movie release" },
      { prompt: "A restaurant offers free meals to anyone who can ______.", answer: "Finish an enormous burger" },
      { prompt: "A couple accidentally bought the same house they had sold ______.", answer: "Years earlier" },
      { prompt: "Scientists discovered goats can recognize ______.", answer: "Human emotions" },
      { prompt: "A man found a winning lottery ticket inside ______.", answer: "An old jacket pocket" },
      { prompt: "A city built an overpass specifically for ______.", answer: "Wildlife" },
      { prompt: "A woman discovered a secret apartment above ______.", answer: "A shopping mall" },
      { prompt: "A thief was identified after leaving behind ______.", answer: "A selfie on the victim's phone" },
      { prompt: "An old suitcase purchased at an auction turned out to contain ______.", answer: "Rare historical documents" },

      { prompt: "In Switzerland, it's illegal to own only one ______.", answer: "Guinea pig" },
      { prompt: "In France, it's technically legal to marry a ______ under special circumstances.", answer: "Dead person" },
      { prompt: "In Australia, it's illegal to disturb a wedding by ______.", answer: "Throwing confetti at the couple without permission" },
      { prompt: "In Singapore, selling ______ is banned.", answer: "Chewing gum" },
      { prompt: "In Venice, feeding ______ can result in a fine.", answer: "Pigeons" },
      { prompt: "In Japan, companies can get in trouble if employees become too ______.", answer: "Overworked" },
      { prompt: "In Alabama, it's illegal to drive while ______.", answer: "Blindfolded" },
      { prompt: "In Arizona, cutting down someone else's ______ can lead to serious penalties.", answer: "Cactus" },
      { prompt: "In Thailand, it's illegal to step on ______.", answer: "Money" },
      { prompt: "In Canada, paying with too many ______ can be refused by a business.", answer: "Coins" },

      { prompt: "In Germany, running out of fuel on the ______ is illegal.", answer: "Autobahn" },
      { prompt: "In Denmark, drivers are legally required to check for ______ before starting their car.", answer: "Children sleeping underneath" },
      { prompt: "In Scotland, if someone knocks on your door claiming to need a ______, tradition says you should help.", answer: "Bathroom" },
      { prompt: "In Italy, some cities require dog owners to walk their dogs at least ______.", answer: "Once a day" },
      { prompt: "In Greece, wearing high heels is banned at certain ______.", answer: "Ancient monuments" },
      { prompt: "In Finland, speeding fines are sometimes based on your ______.", answer: "Income" },
      { prompt: "In England, handling a ______ suspiciously can technically violate an old law.", answer: "Salmon" },
      { prompt: "In France, naming a pig ______ is prohibited.", answer: "Napoleon" },
      { prompt: "In Oklahoma, making ugly faces at a ______ can technically be illegal.", answer: "Dog" },
      { prompt: "In Florida, parking an elephant at a parking meter requires ______.", answer: "Paying the meter" },

      { prompt: "In Switzerland, flushing the toilet late at night in some apartments may be considered ______.", answer: "Noise pollution" },
      { prompt: "In Samoa, forgetting your wife's ______ was once considered an offense.", answer: "Birthday" },
      { prompt: "In New Zealand, some farmers have been fined for dressing sheep in ______.", answer: "Costumes" },
      { prompt: "In Spain, building a sandcastle on certain beaches without permission can earn you a ______.", answer: "Fine" },
      { prompt: "In Dubai, public displays of ______ can result in legal trouble.", answer: "Affection" },
      { prompt: "In California, frogs used in frog-jumping contests cannot be ______ afterward.", answer: "Eaten" },
      { prompt: "In Kentucky, carrying an ice cream cone in your back pocket was once prohibited because it could ______.", answer: "Steal horses" },
      { prompt: "In Minnesota, crossing state lines with a ______ on your head is technically illegal.", answer: "Duck" },
      { prompt: "In France, train stations are legally required to have ______.", answer: "A clock" },
      { prompt: "In Switzerland, some apartment buildings ban ______ after 10 PM.", answer: "Loud recycling" },

      { prompt: "In Australia, some parks prohibit walking more than ______ dogs at once.", answer: "Four" },
      { prompt: "In Iceland, some baby names are rejected unless they're approved by a ______.", answer: "Naming committee" },
      { prompt: "In Germany, insulting someone can lead to a ______.", answer: "Fine" },
      { prompt: "In Singapore, failing to flush a public toilet may result in a ______.", answer: "Fine" },
      { prompt: "In France, ketchup is restricted in many ______.", answer: "School cafeterias" },
      { prompt: "In Italy, feeding ______ near historic landmarks is prohibited.", answer: "Pigeons" },
      { prompt: "In Ohio, getting a fish drunk was once considered ______.", answer: "Illegal" },
      { prompt: "In Vermont, women once needed written permission from their husbands to wear ______.", answer: "False teeth" },
      { prompt: "In Georgia, it's illegal to eat fried chicken using ______.", answer: "A fork" },
      { prompt: "In England, allowing your chickens to cross the road may violate ______.", answer: "Local bylaws" },

      { prompt: "In Norway, television commercials aimed directly at ______ are restricted.", answer: "Children" },
      { prompt: "In Switzerland, many apartment buildings require quiet hours for using ______.", answer: "Washing machines" },
      { prompt: "In Japan, many public pools prohibit people with visible ______.", answer: "Tattoos" },
      { prompt: "In Italy, sitting on famous ______ is prohibited.", answer: "Historic monuments" },
      { prompt: "In the UAE, taking photos of strangers without permission can lead to ______.", answer: "Legal penalties" },
      { prompt: "In Canada, some towns ban leaving your car ______.", answer: "Unlocked" },
      { prompt: "In Germany, prison escape itself isn't punished because it's considered a basic ______.", answer: "Human instinct" },
      { prompt: "In Switzerland, social animals like guinea pigs are encouraged to have a ______.", answer: "Companion" },
      { prompt: "In Scotland, an old law supposedly requires you to help someone requesting to use your ______.", answer: "Toilet" },
      { prompt: "In France, schools traditionally serve multiple courses to encourage ______.", answer: "Healthy eating habits" },

      { prompt: "In Milan, Italy, people are legally required to ______ in public unless attending a funeral or visiting a hospital.", answer: "Smile" },
      { prompt: "In Switzerland, you cannot keep a single ______ because they get lonely.", answer: "Parrot" },
      { prompt: "In Victoria, Australia, only licensed electricians are legally allowed to ______.", answer: "Change a light bulb" },
      { prompt: "In Florida, tying an ______ to a parking meter requires paying the meter.", answer: "Elephant" },
      { prompt: "In Switzerland, it's illegal to ______ after 10 PM in some apartment buildings.", answer: "Flush the toilet" },
      { prompt: "In Oklahoma, you can be fined for making funny faces at a ______.", answer: "Dog" },
      { prompt: "In France, schools were once discouraged from serving ______ with lunch.", answer: "Ketchup" },
      { prompt: "In Denmark, before driving, motorists are legally expected to check for ______.", answer: "Children beneath the car" },
      { prompt: "In Japan, many hot springs refuse entry to guests with visible ______.", answer: "Tattoos" },
      { prompt: "In Germany, it is illegal to stop unnecessarily on the ______.", answer: "Autobahn" },

      { prompt: "In Alabama, driving the wrong way down a one-way street while holding a ______ was once prohibited.", answer: "Lantern" },
      { prompt: "In Alaska, waking a sleeping ______ just to take a photo is illegal.", answer: "Bear" },
      { prompt: "In Arizona, damaging a giant ______ can lead to prison time.", answer: "Saguaro cactus" },
      { prompt: "In Georgia, eating fried chicken with anything other than your ______ was once banned in one town.", answer: "Hands" },
      { prompt: "In Indiana, catching a fish with your ______ is illegal.", answer: "Bare hands" },
      { prompt: "In Kentucky, carrying an ice cream cone in your back pocket was banned because it could ______.", answer: "Lure away horses" },
      { prompt: "In Louisiana, stealing someone's ______ could result in additional penalties.", answer: "Alligator" },
      { prompt: "In Minnesota, sleeping ______ is prohibited under an old law.", answer: "Naked" },
      { prompt: "In Nevada, riding a ______ on the highway is prohibited.", answer: "Camel" },
      { prompt: "In Ohio, getting a ______ drunk was once illegal.", answer: "Fish" },

      { prompt: "In Tennessee, sharing your Netflix password might violate ______.", answer: "State law" },
      { prompt: "In Texas, selling your ______ is illegal.", answer: "Eyes" },
      { prompt: "In Utah, birds technically have the right of ______ on highways.", answer: "Way" },
      { prompt: "In Wisconsin, serving ______ as apple pie is restricted.", answer: "Cheese substitutes" },
      { prompt: "In England, handling a salmon in suspicious circumstances is ______.", answer: "Illegal" },
      { prompt: "In Scotland, an old law says you should allow someone to use your ______ if they ask.", answer: "Toilet" },
      { prompt: "In Wales, entering a castle after closing hours may result in ______.", answer: "A Fine" },
      { prompt: "In Norway, TV ads aimed directly at ______ are prohibited.", answer: "Children" },
      { prompt: "In Sweden, repainting your house may require approval if it's considered ______.", answer: "Historically significant" },
      { prompt: "In Iceland, babies' names must often be approved by a national ______.", answer: "Naming committee" },

      { prompt: "In Spain, reserving a beach spot by leaving your ______ can earn you a fine.", answer: "Umbrella" },
      { prompt: "In Venice, feeding ______ is prohibited in popular tourist areas.", answer: "Pigeons" },
      { prompt: "In Thailand, stepping on ______ is considered illegal because it bears the King's image.", answer: "Currency" },
      { prompt: "In Singapore, failing to flush a public toilet can result in a ______.", answer: "Fine" },
      { prompt: "In Dubai, photographing people without permission can lead to ______.", answer: "Criminal charges" },
      { prompt: "In Canada, paying with too many ______ may legally be refused.", answer: "Pennies" },
      { prompt: "In New Zealand, some roads have signs warning drivers to watch for ______.", answer: "Penguins" },
      { prompt: "In Brazil, jury duty is considered both a civic duty and a ______.", answer: "Constitutional obligation" },
      { prompt: "In Switzerland, many apartment buildings prohibit using the ______ late at night.", answer: "Washing machine" },
      { prompt: "In France, train stations are legally required to display a ______.", answer: "Clock" },

      { prompt: "In Australia, some beaches prohibit bringing ______ onto the sand.", answer: "Glass bottles" },
      { prompt: "In Germany, escaping from prison isn't itself illegal because freedom is considered a basic ______.", answer: "Human instinct" },
      { prompt: "In Finland, traffic fines for serious speeding may depend on your ______.", answer: "Income" },
      { prompt: "In Italy, swimming in many historic fountains is ______.", answer: "Illegal" },
      { prompt: "In the UAE, insulting someone online can result in ______.", answer: "A large fine" },
      { prompt: "In Japan, companies can face criticism for employees working too much because of ______.", answer: "Karoshi (death from overwork)" },
      { prompt: "In Switzerland, guinea pigs are encouraged to live with at least one ______.", answer: "Companion" },
      { prompt: "In France, naming your pig ______ was once prohibited by law.", answer: "Napoleon" },
      { prompt: "In Greece, wearing high heels at certain ancient sites is prohibited to protect the ______.", answer: "Stone" },
      { prompt: "In Denmark, headlights must be on while driving, even during ______.", answer: "Daylight" },
    ],
  },
  wordgames: {
    name: "Word Games",
    emoji: "🔤",
    blurb: "Obscure real words. Bluff a definition, spot the truth.",
    questions: [
      { prompt: "Define the real word: \"Petrichor\"", answer: "The pleasant smell of rain on dry earth" },
      { prompt: "Define the real word: \"Gubbins\"", answer: "Miscellaneous bits and bobs" },
      { prompt: "Define the real word: \"Collywobbles\"", answer: "A nervous stomach ache" },
      { prompt: "Define the real word: \"Snollygoster\"", answer: "A shrewd, unprincipled person" },
      { prompt: "Define the real word: \"Widdershins\"", answer: "Moving in an anticlockwise direction" },
      { prompt: "Define the real word: \"Brontide\"", answer: "The low rumble of distant thunder" },
      { prompt: "Define the real word: \"Mumpsimus\"", answer: "Someone who clings to a mistaken belief" },
      { prompt: "Define the real word: \"Nudiustertian\"", answer: "Relating to the day before yesterday" },
      { prompt: "Define the real word: \"Pandiculation\"", answer: "The act of stretching and yawning" },
      { prompt: "Define the real word: \"Ultracrepidarian\"", answer: "One who gives opinions beyond their knowledge" },
      { prompt: "Define the real word: \"Cwtch\"", answer: "A cosy Welsh cuddle" },
      { prompt: "Define the real word: \"Zenzizenzizenzic\"", answer: "A number raised to the eighth power" },
      { prompt: "Define the real word: \"Petrichor\"", answer: "The pleasant smell of rain on dry earth" },
      { prompt: "Define the real word: \"Aglet\"", answer: "The plastic tip of a shoelace" },
      { prompt: "Define the real word: \"Defenestration\"", answer: "The act of throwing someone or something out of a window" },
      { prompt: "Define the real word: \"Callipygian\"", answer: "Having well-shaped buttocks" },
      { prompt: "Define the real word: \"Apricity\"", answer: "The warmth of the sun in winter" },
      { prompt: "Define the real word: \"Cockalorum\"", answer: "A self-important little man" },
      { prompt: "Define the real word: \"Mumpsimus\"", answer: "A person who stubbornly sticks to a mistaken belief" },
      { prompt: "Define the real word: \"Limerence\"", answer: "The intense feeling of romantic infatuation" },
      { prompt: "Define the real word: \"Clinomania\"", answer: "An excessive desire to stay in bed" },
      { prompt: "Define the real word: \"Uhtceare\"", answer: "Lying awake worrying before dawn" },

      { prompt: "Define the real word: \"Mamihlapinatapai\"", answer: "A shared look where two people want the other to make the first move" },
      { prompt: "Define the real word: \"Ecdysiast\"", answer: "A professional striptease performer" },
      { prompt: "Define the real word: \"Bibliosmia\"", answer: "The smell of old books" },
      { prompt: "Define the real word: \"Nudiustertian\"", answer: "Referring to the day before yesterday" },
      { prompt: "Define the real word: \"Pusillanimous\"", answer: "Showing a lack of courage" },
      { prompt: "Define the real word: \"Quomodocunquizing\"", answer: "Making money by any possible means" },
      { prompt: "Define the real word: \"Snollygoster\"", answer: "A clever but unprincipled politician" },
      { prompt: "Define the real word: \"Gobemouche\"", answer: "A very gullible person" },
      { prompt: "Define the real word: \"Xertz\"", answer: "To gulp something down quickly" },
      { prompt: "Define the real word: \"Wamblecropt\"", answer: "Suffering from indigestion" },

      { prompt: "Define the real word: \"Mondegreen\"", answer: "A misheard song lyric" },
      { prompt: "Define the real word: \"Nyctophile\"", answer: "A person who loves the night" },
      { prompt: "Define the real word: \"Psithurism\"", answer: "The sound of leaves rustling in the wind" },
      { prompt: "Define the real word: \"Ultracrepidarian\"", answer: "Someone who gives opinions beyond their knowledge" },
      { prompt: "Define the real word: \"Crapulence\"", answer: "Feeling sick after eating or drinking too much" },
      { prompt: "Define the real word: \"Accismus\"", answer: "Pretending to refuse something you actually want" },
      { prompt: "Define the real word: \"Peregrinate\"", answer: "To travel from place to place" },
      { prompt: "Define the real word: \"Lethologica\"", answer: "The inability to remember a word" },
      { prompt: "Define the real word: \"Nibling\"", answer: "A niece or nephew" },
      { prompt: "Define the real word: \"Philocalist\"", answer: "A lover of beauty" },

      { prompt: "Define the real word: \"Cacography\"", answer: "Bad handwriting or poor spelling" },
      { prompt: "Define the real word: \"Osculate\"", answer: "To kiss" },
      { prompt: "Define the real word: \"Borborygmus\"", answer: "The rumbling sound made by your stomach" },
      { prompt: "Define the real word: \"Ephemeral\"", answer: "Lasting for a very short time" },
      { prompt: "Define the real word: \"Paraprosdokian\"", answer: "A sentence with an unexpected ending" },
      { prompt: "Define the real word: \"Resfeber\"", answer: "The restless excitement before a journey" },
      { prompt: "Define the real word: \"Acnestis\"", answer: "The part of your back you can't reach to scratch" },
      { prompt: "Define the real word: \"Tittynope\"", answer: "A small leftover amount of food or drink" },
      { prompt: "Define the real word: \"Overmorrow\"", answer: "The day after tomorrow" },
      { prompt: "Define the real word: \"Agastopia\"", answer: "Admiration of a particular part of someone's body" },

      { prompt: "Define the real word: \"Ratoon\"", answer: "A new shoot growing from the base of a plant" },
      { prompt: "Define the real word: \"Pandiculation\"", answer: "Stretching and yawning at the same time" },
      { prompt: "Define the real word: \"Kakorrhaphiophobia\"", answer: "The fear of failure" },
      { prompt: "Define the real word: \"Zarf\"", answer: "A decorative holder for a coffee cup" },
      { prompt: "Define the real word: \"Selenophile\"", answer: "A person who loves the moon" },
      { prompt: "Define the real word: \"Exulansis\"", answer: "Giving up trying to explain yourself because nobody understands" },
      { prompt: "Define the real word: \"Dysania\"", answer: "Finding it hard to get out of bed in the morning" },
      { prompt: "Define the real word: \"Furtive\"", answer: "Attempting to avoid notice or attention" },
      { prompt: "Define the real word: \"Susurrus\"", answer: "A whispering or rustling sound" },
      { prompt: "Define the real word: \"Weltschmerz\"", answer: "A feeling of melancholy about the state of the world" },

      { prompt: "Define the real word: \"Absquatulate\"", answer: "To leave suddenly or flee" },
      { prompt: "Define the real word: \"Abecedarian\"", answer: "A person learning the alphabet or a beginner" },
      { prompt: "Define the real word: \"Ailurophile\"", answer: "A person who loves cats" },
      { prompt: "Define the real word: \"Acrophobia\"", answer: "Fear of heights" },
      { prompt: "Define the real word: \"Bumbershoot\"", answer: "An umbrella" },
      { prompt: "Define the real word: \"Brouhaha\"", answer: "A noisy uproar or commotion" },
      { prompt: "Define the real word: \"Cacophony\"", answer: "A harsh mixture of unpleasant sounds" },
      { prompt: "Define the real word: \"Chthonic\"", answer: "Relating to the underworld" },
      { prompt: "Define the real word: \"Dactyl\"", answer: "A poetic foot or a finger or toe" },
      { prompt: "Define the real word: \"Ebullient\"", answer: "Cheerful and full of energy" },

      { prompt: "Define the real word: \"Eidetic\"", answer: "Relating to exceptionally vivid memory" },
      { prompt: "Define the real word: \"Effulgent\"", answer: "Shining brightly" },
      { prompt: "Define the real word: \"Floccinaucinihilipilification\"", answer: "The act of considering something worthless" },
      { prompt: "Define the real word: \"Fipple\"", answer: "The mouthpiece of a recorder or whistle" },
      { prompt: "Define the real word: \"Garrulous\"", answer: "Excessively talkative" },
      { prompt: "Define the real word: \"Hiraeth\"", answer: "A homesickness for a place that may never have existed" },
      { prompt: "Define the real word: \"Ipsedixitism\"", answer: "Belief based solely on someone's authority" },
      { prompt: "Define the real word: \"Jentacular\"", answer: "Relating to breakfast" },
      { prompt: "Define the real word: \"Kenopsia\"", answer: "The eerie feeling of an abandoned place" },
      { prompt: "Define the real word: \"Lagniappe\"", answer: "A small bonus gift" },

      { prompt: "Define the real word: \"Lugubrious\"", answer: "Looking or sounding sad" },
      { prompt: "Define the real word: \"Mellifluous\"", answer: "Pleasingly smooth and musical" },
      { prompt: "Define the real word: \"Nemophilist\"", answer: "A lover of forests" },
      { prompt: "Define the real word: \"Obfuscate\"", answer: "To make something confusing" },
      { prompt: "Define the real word: \"Omphaloskepsis\"", answer: "Contemplating one's own navel" },
      { prompt: "Define the real word: \"Palimpsest\"", answer: "A manuscript written over an older erased one" },
      { prompt: "Define the real word: \"Quire\"", answer: "Twenty-four or twenty-five sheets of paper" },
      { prompt: "Define the real word: \"Raconteur\"", answer: "A skilled storyteller" },
      { prompt: "Define the real word: \"Sempiternal\"", answer: "Everlasting or eternal" },
      { prompt: "Define the real word: \"Skirl\"", answer: "A shrill wailing sound" },

      { prompt: "Define the real word: \"Tintinnabulation\"", answer: "The ringing of bells" },
      { prompt: "Define the real word: \"Ulotrichous\"", answer: "Having tightly curled hair" },
      { prompt: "Define the real word: \"Vellichor\"", answer: "The strange wistfulness of used bookstores" },
      { prompt: "Define the real word: \"Whiffling\"", answer: "Blowing in gusts or puffs" },
      { prompt: "Define the real word: \"Xenial\"", answer: "Friendly to guests or strangers" },
      { prompt: "Define the real word: \"Yen\"", answer: "A strong desire or craving" },
      { prompt: "Define the real word: \"Zephyr\"", answer: "A gentle breeze" },
      { prompt: "Define the real word: \"Zugzwang\"", answer: "A situation where any move makes things worse" },
      { prompt: "Define the real word: \"Acnestis\"", answer: "The spot on your back you can't reach to scratch" },
      { prompt: "Define the real word: \"Brontide\"", answer: "A distant rumbling sound like thunder" },

      { prompt: "Define the real word: \"Crepuscular\"", answer: "Active during twilight" },
      { prompt: "Define the real word: \"Dord\"", answer: "A famous ghost word mistakenly added to a dictionary" },
      { prompt: "Define the real word: \"Eucatastrophe\"", answer: "A sudden happy turn in a story" },
      { prompt: "Define the real word: \"Fernweh\"", answer: "A longing to travel to distant places" },
      { prompt: "Define the real word: \"Grumphie\"", answer: "A gloomy or sulky person" },
      { prompt: "Define the real word: \"Hypnagogic\"", answer: "Relating to the state before falling asleep" },
      { prompt: "Define the real word: \"Interrobang\"", answer: "A punctuation mark combining ? and !" },
      { prompt: "Define the real word: \"Jocund\"", answer: "Cheerful and lighthearted" },
      { prompt: "Define the real word: \"Luculent\"", answer: "Clear and easy to understand" },
      { prompt: "Define the real word: \"Murmuration\"", answer: "A flock of starlings flying together" },

      { prompt: "Define the real word: \"Pogonotrophy\"", answer: "The act of growing a beard" },
      { prompt: "Define the real word: \"Anemoia\"", answer: "Nostalgia for a time you never experienced" },
      { prompt: "Define the real word: \"Cynosure\"", answer: "The center of attention or admiration" },
      { prompt: "Define the real word: \"Dendrochronology\"", answer: "The science of dating trees by their growth rings" },
      { prompt: "Define the real word: \"Epistolary\"", answer: "Relating to letters or letter writing" },
      { prompt: "Define the real word: \"Fugacious\"", answer: "Lasting only a short time" },
      { prompt: "Define the real word: \"Gallimaufry\"", answer: "A confused mixture of unrelated things" },
      { prompt: "Define the real word: \"Haptics\"", answer: "The science of touch" },
      { prompt: "Define the real word: \"Imbroglio\"", answer: "A confusing or complicated situation" },
      { prompt: "Define the real word: \"Jargonelle\"", answer: "A variety of pear" },

      { prompt: "Define the real word: \"Kairos\"", answer: "The perfect or opportune moment" },
      { prompt: "Define the real word: \"Lachrymose\"", answer: "Tearful or inclined to cry" },
      { prompt: "Define the real word: \"Mumpsimus\"", answer: "A stubborn adherence to an incorrect belief" },
      { prompt: "Define the real word: \"Noctambulist\"", answer: "A sleepwalker" },
      { prompt: "Define the real word: \"Oenomel\"", answer: "Wine mixed with honey" },
      { prompt: "Define the real word: \"Panacea\"", answer: "A remedy for all problems or diseases" },
      { prompt: "Define the real word: \"Quotidian\"", answer: "Occurring every day; ordinary" },
      { prompt: "Define the real word: \"Rubicund\"", answer: "Having a healthy reddish complexion" },
      { prompt: "Define the real word: \"Spelunking\"", answer: "Exploring caves" },
      { prompt: "Define the real word: \"Tergiversate\"", answer: "To evade or change one's position" },

      { prompt: "Define the real word: \"Ucalegon\"", answer: "A neighbor whose house is on fire" },
      { prompt: "Define the real word: \"Vituperate\"", answer: "To criticize harshly" },
      { prompt: "Define the real word: \"Widdershins\"", answer: "In a direction opposite to clockwise" },
      { prompt: "Define the real word: \"Xylophagous\"", answer: "Feeding on wood" },
      { prompt: "Define the real word: \"Ylem\"", answer: "The primordial matter from which the universe formed" },
      { prompt: "Define the real word: \"Zoanthropy\"", answer: "A delusion of being an animal" },
      { prompt: "Define the real word: \"Aestivate\"", answer: "To spend the summer in a dormant state" },
      { prompt: "Define the real word: \"Boustrophedon\"", answer: "Writing alternate lines in opposite directions" },
      { prompt: "Define the real word: \"Catoptromancy\"", answer: "Divination using mirrors" },
      { prompt: "Define the real word: \"Druthers\"", answer: "Personal preference" },

      { prompt: "Define the real word: \"Eleemosynary\"", answer: "Relating to charity or donations" },
      { prompt: "Define the real word: \"Farinaceous\"", answer: "Containing or resembling flour" },
      { prompt: "Define the real word: \"Glabrous\"", answer: "Smooth and hairless" },
      { prompt: "Define the real word: \"Heliophile\"", answer: "A lover of sunlight" },
      { prompt: "Define the real word: \"Incunabula\"", answer: "Books printed before the year 1501" },
      { prompt: "Define the real word: \"Jeremiad\"", answer: "A long lament or complaint" },
      { prompt: "Define the real word: \"Kakistocracy\"", answer: "Government by the least qualified people" },
      { prompt: "Define the real word: \"Limn\"", answer: "To paint or describe in detail" },
      { prompt: "Define the real word: \"Mumpsimus\"", answer: "An outdated custom stubbornly followed" },
      { prompt: "Define the real word: \"Nictitate\"", answer: "To blink or wink" },

      { prompt: "Define the real word: \"Opsimath\"", answer: "A person who begins learning late in life" },
      { prompt: "Define the real word: \"Peregrination\"", answer: "A long journey or wandering" },
      { prompt: "Define the real word: \"Quincunx\"", answer: "An arrangement of five objects with four at the corners and one in the center" },
      { prompt: "Define the real word: \"Rostrum\"", answer: "A raised platform for public speaking" },
      { prompt: "Define the real word: \"Sialoquent\"", answer: "Spraying saliva while speaking" },
      { prompt: "Define the real word: \"Thalassophile\"", answer: "A person who loves the sea" },
      { prompt: "Define the real word: \"Umbriferous\"", answer: "Providing shade" },
      { prompt: "Define the real word: \"Verbigeration\"", answer: "The meaningless repetition of words or phrases" },
      { prompt: "Define the real word: \"Wamble\"", answer: "To feel nauseous" },
      { prompt: "Define the real word: \"Yonderly\"", answer: "Mentally absent or dreamy" },
    ],
  },
};
